In [1]:
import numpy as np

### Creation of Array

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a=[1,2,3,4,5]

In [5]:
a

[1, 2, 3, 4, 5]

In [6]:
arr=np.array(a)
arr

array([1, 2, 3, 4, 5])

In [8]:
list=[[10,20,30],[40,50,60],[70,80,90]]

In [9]:
list

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [10]:
arr=np.array(list)

In [11]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### Array Generation

##### Using arange()

In [14]:
arr=np.arange(1,50,2)

In [15]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

##### using Ones and zeros

In [16]:
arr=np.zeros((5,6))

In [17]:
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr=np.ones((5,6))

In [20]:
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

##### using Linspace

In [24]:
arr=np.linspace(0,50,20)

In [25]:
arr

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

##### using Random

In [28]:
arr=np.random.randn(10)

In [29]:
arr

array([-0.98140829,  1.66174032,  1.58743924,  0.25546538, -0.25124824,
       -0.60680168, -0.26875885,  0.56472781,  0.29697782, -0.2940402 ])

In [30]:
arr=np.random.randint(10,20,5)

In [31]:
arr

array([13, 12, 15, 10, 16], dtype=int32)

### Array Attribute

In [53]:
arr=np.arange(1,31)

In [54]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr.dtype

dtype('int64')

In [56]:
arr.size

30

In [57]:
arr.shape

(30,)

In [60]:
arr1=arr.reshape((6,5))

In [61]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Array Method

In [63]:
arr1.shape

(6, 5)

In [66]:
arr1.size

30

In [68]:
arr.mean()

np.float64(15.5)

In [69]:
arr.max()

np.int64(30)

In [70]:
arr.min()

np.int64(1)

In [71]:
arr.sum()

np.int64(465)

In [72]:
np.sum(arr1,axis=1)

array([ 15,  40,  65,  90, 115, 140])

In [73]:
arr.std()

np.float64(8.65544144839919)

In [74]:
arr1.argmax()

np.int64(29)

In [75]:
arr1.argmin()

np.int64(0)

#####  INDEXING & SLICING OF VECTORS (1D Arrays) 

In [76]:
arr = np.arange(11,21)

In [77]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [81]:
arr_slice=arr[1:]

In [82]:
arr_slice

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [85]:
arr_slice=arr[:-1]

In [86]:
arr_slice

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [87]:
arr_slice=arr[3:7]

In [88]:
arr_slice

array([14, 15, 16, 17])

In [89]:
arr[4] 

np.int64(15)

### Create a matrix

In [91]:
arr = np.arange(1,31).reshape(6,5) 

In [92]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

##### Slice a Sub-Matrix

In [94]:
slice = arr[3:, 3:]

In [95]:
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [96]:
arr[:,2] 

array([ 3,  8, 13, 18, 23, 28])

#####  BOOLEAN INDEXING

In [98]:
arr = np.arange(11,21) 

In [99]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [101]:
bool_index = arr % 2 == 0 

In [102]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [103]:
arr = arr[bool_index]

In [104]:
arr

array([12, 14, 16, 18, 20])

##### ARRAY OPERATIONS

###### Arithmetic Operations

In [106]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [108]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [109]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [110]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [111]:
a1 / a2 

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [112]:
a1 // a2

array([0, 0, 0, 0, 0])

In [113]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [115]:
a2 * 2

array([12, 14, 16, 18, 20])

### BROADCASTING

In [116]:
l = [10,20,30,40] 

In [117]:
l

[10, 20, 30, 40]

In [118]:
arr = np.array(l) 

In [119]:
arr

array([10, 20, 30, 40])

In [120]:
arr + 10 

array([20, 30, 40, 50])

In [121]:
arr2 = np.arange(1,26).reshape(5,5)

In [122]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
arr2 = arr2 + 10 

In [124]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

##### Deep and Shallow Copy 

In [125]:
a = np.arange(1,21)

In [126]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [127]:
slice = a[:5]

In [128]:
slice

array([1, 2, 3, 4, 5])

In [129]:
slice*10

array([10, 20, 30, 40, 50])

In [131]:
slice

array([1, 2, 3, 4, 5])

In [133]:
b = a.copy() 

In [134]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [135]:
b[0]=99

In [136]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

##### Matrix Operations

###### Dot Product

In [140]:
a1 = np.array([1,2,3,4]).reshape((2,2))
a2 = np.array([6,7,8,9]).reshape((2,2))


In [141]:
np.dot(a1, a2) 

array([[22, 25],
       [50, 57]])

In [143]:
a1.T

array([[1, 3],
       [2, 4]])

### Advanced Array Manipulation 

######  STACKING ARRAYS (Combine arrays) 

In [144]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [145]:
np.hstack((a1,a2)) 

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

In [146]:
c = np.arange(16).reshape(4,4) 
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [147]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

###  General NumPy Questions

In [148]:
data = np.array([ 
    [18, 85, 78],   
    [19, 92, 88],   
    [17, 76, 95],   
    [18, 65, 70],   
    [20, 90, 85]    
]) 

In [149]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

##### 1.Get the shape of the matrix.
##### 2. Find the average age of students. 
##### 3. Extract Math marks of all students.
##### 4. Find the highest Science mark
##### 5. Get details of the student who scored more than 90 in Math. 
##### 6. Increase Math marks of all students by 5.
##### 7. Find how many students are younger than 19.
##### 8. Average marks in each subject (column-wise mean). 
##### 9. Students who scored at least 80 in both Math & Science.
##### 10. Replace all Science marks < 75 with 0.
#####  Create a NumPy array with numbers from 10 to 30. 
#####  Create an array of shape (3,3) filled with only 5.
#####  Create a 1D array of 8 zeros.
#####  Given arr = np.arange(20), extract values from index 5 to 12.
#####  Extract every 3rd value from the same array.
#####  Create a 4×4 matrix and extract the 2nd column.
#####  From arr = np.arange(1,16), extract all even numbers.
#####  Extract values greater than 10. 
#####  Add two arrays: [1,2,3,4] and [10,20,30,40] 
#####  Multiply every element of [5,10,15,20] by 3. 
#####  Add 5 to a matrix of shape (3,3).
#####  Find the mean, max, min of the array [12, 5, 29, 33, 7]. 
#####  Find row-wise sum of a 3×3 matrix.
#####  Perform matrix multiplication of
#####  Find the transpose of the matrix A above.
#####  Vertically stack [1,2,3] and [4,5,6] 
#####  Horizontally split a 4×4 matrix into 4 parts.
#####  Extract Math marks.
#####  Find the highest Science mark.
#####  Extract students who scored ≥ 80 in both subjects.

In [150]:
data.shape 

(5, 3)

In [151]:
data[:, 0].mean() 

np.float64(18.4)

In [ ]:
data[:, 1] 

In [ ]:
data[:, 2].max()

In [ ]:
data[data[:, 1] > 90] 

In [ ]:
data[:, 1] = data[:, 1] + 5 

In [ ]:
np.sum(data[:, 0] < 19) 

In [ ]:
data.mean(axis=0) 

In [ ]:
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)] 

In [ ]:
data[data[:, 2] < 75, 2] = 0 

In [ ]:
arr = np.arange(10, 31) 

In [ ]:
arr = np.full((3,3), 5)

In [ ]:
np.zeros(8) 

In [ ]:
arr = np.arange(20)

In [ ]:
arr[::3] 

In [ ]:
m = np.arange(16).reshape(4,4) 
m[:, 1] 

In [ ]:
arr[arr % 2 == 0]

In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
a + b 

In [ ]:
arr = np.array([5,10,15,20]) 
arr * 3 

In [ ]:
m = np.arange(9).reshape(3,3) 
m + 5 

In [ ]:
arr = np.array([12, 5, 29, 33, 7]) 
arr.mean(), arr.max(), arr.min()

In [ ]:
m = np.arange(1,10).reshape(3,3) 
np.sum(m, axis=1) 

In [ ]:
A = np.array([[1,2],[3,4]]) 
B = np.array([[5,6],[7,8]]) 
np.dot(A, B) 

In [ ]:
A.T 

In [ ]:
a = np.array([1,2,3]) 
b = np.array([4,5,6]) 
np.vstack((a,b)) 

In [ ]:
m = np.arange(16).reshape(4,4) 
np.hsplit(m, 4) 

In [ ]:
data[:, 1] 

In [ ]:
data[:, 2].max() 

In [ ]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)] 

In [ ]:
data[data[:,2] < 75, 2] = 0